### ISSUE TITLE
Named States

### ISSUE THREAD

**Issue by curropar** [encadyma/chronos#1]
Hi, 
I know development is on hold, but you didn't say until when, and this addon is great!

Question, or request: would be possible, and easy to implement, to give a descriptive name to the states? So instead of saving them with a DateTime name you could save it as "Summer Holidays", or "Super secret project" - because we all have one of those! xD 

Thanks!

**Comment by encadyma** [comment]
Hey @curropar, glad that Chronos is working out for you! I'm a fan of named states. They shouldn't be too hard to implement, so if time permits, I can roll it out as v1.1.2 by the end of the week. Once it's rolled out, I'll close the Github issue so you can keep track. Thank you for the idea 😄.

If possible, could I ask for a small piece of feedback in return? I'm especially interested to hear more about how people are using Chronos in their browsing workflows. If I could get a sense of what's working for users, then I can plan out future versions and resume development.

Otherwise, thank you for your suggestion!

**Comment by curropar** [comment]
Hi! Wow, by the end of the week? That would be quick for an on hold project! ;-) 

Sure I can give you feedback! I've recently switched back from Chrome to Firefox, and in Chrome I was using [this [](addon](https://chrome.google.com/webstore/detail/tabs-outliner/eggkanocgddhmamlbiijnphhppkpkmkl?pageId=109072947181037956368&hl=en-US),) and I've been looking for anything similar (not having the time and/or coding knowledge to do it myself). 

That's the starting point. About the use itself: I'm a sysadmin, and when I search on the internet for documentation/information, I tend to do a search on Google, then I start to open several tabs to visit them later. Plus I've a couple of sites for corporate use that I've always open (ticketing tool, monitoring...). So I found myself everyday with more than 20 tabs easily, and in Chrome that was a huge problem with memory.

With that addon I would close windows (fortunately, I also tend to open several windows and group the tabs by subject) knowing I can restore them later, no matter if I've even closed Chrome (or has it crashed!) at some point. 

So in your addon, the option "Save and close this window for later" is exactly what I was looking for! Not that Firefox has the problem with the memory that Chrome has, but I've get used to that way of work.

**Comment by curropar** [comment]
You wanted a "small piece of feedback", I may have forgot what "small" means!

**Comment by encadyma** [comment]
Haha, no worries. I actually appreciate your long feedback. I find myself using the website blocking features more, so it's interesting to hear a different use case from someone else. Was the Chrome extension [Tabby](https://chrome.google.com/webstore/detail/tabby/jagodfglaafhkohchlcbloacemmicjal?utm_source=chrome-ntp-icon) or [Session Manager](https://chrome.google.com/webstore/detail/session-manager/bbcnbpafconjjigibnhbfmmgdbbkcjfi?utm_source=chrome-ntp-icon)? I remember trying one of these extensions (forgot which one) when I had used Chrome.

There's a great chance in the future that I will work on this add-on again, and when it comes I'll be sure to focus on improving states first! Thanks again for sharing your story.

In the meantime, I've updated Chronos to v1.1.2. Named states are now implemented, and you can even go back and rename your existing states if you need to. Thank you for using Chronos! 

*edit: It won't ask you to name your state when you click the "Save and close this window for later" button (it'll behave just as before), but you can go back to your list of states and rename it from there.

**Comment by curropar** [comment]
Sorry, I forgot to link it: it was [Tabs Outliner](https://chrome.google.com/webstore/detail/tabs-outliner/eggkanocgddhmamlbiijnphhppkpkmkl). 

For me blocking is not that useful, as I work in a room with around 16 people, and because of the position of the desks, my screen is easily viewed by many of them. That is really a stopper if I want to procrastinate. Which I eventually do, but short periods of time, and not everyday.

I just tried the new version, it's exactly what I needed! Thanks for taking the time to do this, and for focusing in states in the future! I really appreciate it!! Keep the good work!
